<?php
header("HTTP/1.0 404 Not found");
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../public/css/style.css">
    <title>Not_found</title>
</head>
<body class="error">
    <h1>Page introuvable</h1>
    <a href="/">Retour a la page d'acceuil</a>
</body>
</html>